<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

// class UserTableSeeder extends Seeder
// {
//     /**
//      * Run the database seeds.
//      */
//     public function run(): void
//     {
//         //
//         $users = [];
//         $numberOfUsers = 50; // Change this to the number of users you want to insert

//         for ($i = 1; $i <= $numberOfUsers; $i++) {
//             $users[] = [
//                 'name' => 'User ' . $i,
//                 'email' => 'user' . $i . '@test.com',
//                 'mobile' => '81123456' . $i,
//                 'is_active' => $i % 2, // Alternate between 0 and 1 for demo
//                 'password' => Hash::make('password'),
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ];
//         }

//         DB::table('users')->insert($users);

//     }
// }

use Spatie\Permission\Models\Role;
use App\Models\User;

class UserTableSeeder extends Seeder
{
    public function run(): void
    {
        $users = [];
        $numberOfUsers = 50;

        for ($i = 1; $i <= $numberOfUsers; $i++) {
            $user = User::create([
                'user_full_name' => 'User ' . $i,
                'user_name' => 'username' . $i,
                'email' => 'user' . $i . '@test.com',
                'is_active' => $i % 2,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Atribuindo a role 'Admin' ao usuário
            $role = Role::findByName('Admin', 'web');
            $user->assignRole($role);
        }

        DB::table('users')->insert([
            [
                'user_full_name' => 'Ivan Goncalves',
                'user_name' => 'ivan.goncalves@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'ivan.goncalves@cornelder.co.mz',
                'created_by' => 'ivan.goncalves@cornelder.co.mz',
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Administrator',
                'user_name' => 'admin',
                'password' => Hash::make('password'),
                'email' => 'admin@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Tecnico',
                'user_name' => 'Tecnico',
                'password' => Hash::make('password'),
                'email' => 'tecnico@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Adelia Guigo',
                'user_name' => 'ago',
                'password' => Hash::make('password'),
                'email' => 'adelia.guigo@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Fernando  Ajape',
                'user_name' => 'fae',
                'password' => Hash::make('password'),
                'email' => 'fernando.ajape@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Joaquim  Sabado',
                'user_name' => 'jso',
                'password' => Hash::make('password'),
                'email' => 'joaquim.sabado@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Ozorio  Inacio',
                'user_name' => 'oio',
                'password' => Hash::make('password'),
                'email' => 'ozorio.inacio@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Nazir Botao',
                'user_name' => 'nbo',
                'password' => Hash::make('password'),
                'email' => 'nazir.botao@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Valentim  Tomas',
                'user_name' => 'vte',
                'password' => Hash::make('password'),
                'email' => 'valentim.tomas@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Simao  Tivane',
                'user_name' => 'ste',
                'password' => Hash::make('password'),
                'email' => 'simao.tivane@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Brito  Miguel',
                'user_name' => 'bml',
                'password' => Hash::make('password'),
                'email' => 'brito.miguel@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Felisberto Mahamba',
                'user_name' => 'fma',
                'password' => Hash::make('password'),
                'email' => 'felisberto.mahamba@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Franque  Vasco',
                'user_name' => 'fvo',
                'password' => Hash::make('password'),
                'email' => 'franque.vasco@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Nancy  Majamanda',
                'user_name' => 'nma',
                'password' => Hash::make('password'),
                'email' => 'nancy.majamanda@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Lucas  Bechica',
                'user_name' => 'lba',
                'password' => Hash::make('password'),
                'email' => 'lucas.bechica@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Victor Alfai',
                'user_name' => 'vai',
                'password' => Hash::make('password'),
                'email' => 'victor.alfai@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Zeca  Tobias',
                'user_name' => 'zts',
                'password' => Hash::make('password'),
                'email' => 'zeca.tobias@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Augusto  Tony',
                'user_name' => 'aty',
                'password' => Hash::make('password'),
                'email' => 'augusto.tony@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Castigo Magumisse',
                'user_name' => 'cme',
                'password' => Hash::make('password'),
                'email' => 'castigo.magumisse@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Celestino  Mualule',
                'user_name' => 'cml',
                'password' => Hash::make('password'),
                'email' => 'celestino.mualule@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Ernesto Ernesto',
                'user_name' => 'eeo',
                'password' => Hash::make('password'),
                'email' => 'ernesto.ernesto@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Isabel Vilanculos',
                'user_name' => 'ivs',
                'password' => Hash::make('password'),
                'email' => 'isabel.vilanculos@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Jelito Vasco',
                'user_name' => 'jvo',
                'password' => Hash::make('password'),
                'email' => 'jelito.vasco@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Pedro Manuel',
                'user_name' => 'pml',
                'password' => Hash::make('password'),
                'email' => 'pedro.manuel@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'test',
                'user_name' => 'test',
                'password' => Hash::make('password'),
                'email' => 'test@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Jose Comissario',
                'user_name' => 'jco',
                'password' => Hash::make('password'),
                'email' => 'jose.comissario@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Ilidio Bochana',
                'user_name' => 'ilidio.bochana@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'ilidio.bochana@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Jonas Alfixa',
                'user_name' => 'jax',
                'password' => Hash::make('password'),
                'email' => 'jonas.alfixa@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Domingos Sitol',
                'user_name' => 'sdl',
                'password' => Hash::make('password'),
                'email' => 'domingos.sitol@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Fundisse Manuel',
                'user_name' => 'fml',
                'password' => Hash::make('password'),
                'email' => 'fundisse.manuel@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Joaquim Guitar',
                'user_name' => 'jgr',
                'password' => Hash::make('password'),
                'email' => 'joaquim.guitar@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Alberto Zie ',
                'user_name' => 'aze',
                'password' => Hash::make('password'),
                'email' => 'alberto.zie@cornelder.co.mz ',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Lucas Alberto',
                'user_name' => 'lao',
                'password' => Hash::make('password'),
                'email' => 'lucas.alberto@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Sabado Roque',
                'user_name' => 'sre',
                'password' => Hash::make('password'),
                'email' => 'sabado.roque@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Sérgio Ambrósio',
                'user_name' => 'sao',
                'password' => Hash::make('password'),
                'email' => 'sergio.ambrosio@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Joaquim Bene',
                'user_name' => 'jbe',
                'password' => Hash::make('password'),
                'email' => 'joaquim.bene@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Inácio Dauce',
                'user_name' => 'ine',
                'password' => Hash::make('password'),
                'email' => 'inacio.dauce@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Lucas manuel',
                'user_name' => 'lml',
                'password' => Hash::make('password'),
                'email' => 'lucas.manuel@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Carmona Magona',
                'user_name' => 'cma',
                'password' => Hash::make('password'),
                'email' => 'carmona.magona@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'José Maria',
                'user_name' => 'jma',
                'password' => Hash::make('password'),
                'email' => 'jose.maria@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Fernando Chiraramire',
                'user_name' => 'fce',
                'password' => Hash::make('password'),
                'email' => 'fernando.chiraramire@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Pedro António',
                'user_name' => 'pao',
                'password' => Hash::make('password'),
                'email' => 'pedro.antonio@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Lucas Machava',
                'user_name' => 'lma',
                'password' => Hash::make('password'),
                'email' => 'lucas.machava@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Geraldo Jardim',
                'user_name' => 'gjm',
                'password' => Hash::make('password'),
                'email' => 'geraldo.jardim@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Izilda Jose',
                'user_name' => 'ije',
                'password' => Hash::make('password'),
                'email' => 'izilda.jose@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Carlos Dique',
                'user_name' => 'cde',
                'password' => Hash::make('password'),
                'email' => 'carlos.dique@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Canisio Magrasse',
                'user_name' => 'cms',
                'password' => Hash::make('password'),
                'email' => 'canisio.magrasse@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Zito Elias',
                'user_name' => 'zes',
                'password' => Hash::make('password'),
                'email' => 'zito.elias@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Fabião Mugai',
                'user_name' => 'fmi',
                'password' => Hash::make('password'),
                'email' => 'fabiao.mugai@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Balbina Sebasti',
                'user_name' => 'bso',
                'password' => Hash::make('password'),
                'email' => 'balbina.sebasti@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Helenio Tomo',
                'user_name' => 'hto',
                'password' => Hash::make('password'),
                'email' => 'helenio.tomo@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Florencia Olesse',
                'user_name' => 'foe',
                'password' => Hash::make('password'),
                'email' => 'florencia.olesse@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Paulo Andessene',
                'user_name' => 'pae',
                'password' => Hash::make('password'),
                'email' => 'paulo.andessene@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Leandro Nhoazane',
                'user_name' => 'lne',
                'password' => Hash::make('password'),
                'email' => 'leandro.nhoazane@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Teresa Amadeu',
                'user_name' => 'tau',
                'password' => Hash::make('password'),
                'email' => 'teresa.amadeu@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'José Gimo',
                'user_name' => 'jgo',
                'password' => Hash::make('password'),
                'email' => 'jose.gimo@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Victor Augusto',
                'user_name' => 'vao',
                'password' => Hash::make('password'),
                'email' => 'victor.augusto@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Taura Pery',
                'user_name' => 'tpy',
                'password' => Hash::make('password'),
                'email' => 'taura.pery@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Victor Milina',
                'user_name' => 'vma',
                'password' => Hash::make('password'),
                'email' => 'victor.milina@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Rumbidzai Lucas',
                'user_name' => 'rls',
                'password' => Hash::make('password'),
                'email' => 'rumbidzai.lucas@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Eduardo Niclosse',
                'user_name' => 'eduardo.miclosse@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'eduardo.miclosse@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Nelo Jeque',
                'user_name' => 'nlj',
                'password' => Hash::make('password'),
                'email' => 'nelo.jeque@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Gilda Sitoe',
                'user_name' => 'gilda.sitoe@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'gilda.sitoe@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Tendai Gumbo',
                'user_name' => 'tendai.gumbo@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'tendai.gumbo@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Augusto Jiquete',
                'user_name' => 'augusto.jiquete@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'augusto.jiquete@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Victor Roque',
                'user_name' => 'victor.roque@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'victor.roque@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Victor Roque',
                'user_name' => 'vre',
                'password' => Hash::make('password'),
                'email' => 'Victor.Roque@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Nelo Kripton Jeque',
                'user_name' => 'Nelo.Jeque@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'Nelo.Jeque@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Rosa Maria Manane',
                'user_name' => 'Rosa.Manane@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'Rosa.Manane@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Helder Abreu',
                'user_name' => 'Helder.Abreu@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'Helder.Abreu@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Luisa Fossate',
                'user_name' => 'Luisa.Fossate@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'Luisa.Fossate@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Pedro Antonio',
                'user_name' => 'Pedro.Antonio@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'Pedro.Antonio@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Guilherme Castro',
                'user_name' => 'Guilherme.Castro@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'guileherme.castro@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Artur Muguiviza',
                'user_name' => 'artur.muguiviza@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'artur.muiguiviza@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'Gomes Marcelino',
                'user_name' => 'gomesmarcelino@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'gomesmarcelino@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'CUSSARA MAMBONGO',
                'user_name' => 'cussara.mambongo',
                'password' => Hash::make('password'),
                'email' => 'cussara.mambongo@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'CRISTINA DAVIVRO',
                'user_name' => 'cristina.davivro',
                'password' => Hash::make('password'),
                'email' => 'cristina.davivro@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'JOAQUIM JOÃO',
                'user_name' => 'joaquim.joao',
                'password' => Hash::make('password'),
                'email' => 'joaquim.joao@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'JOÃO ALBINO',
                'user_name' => 'joao.albino',
                'password' => Hash::make('password'),
                'email' => 'joao.albino@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'MARCELO PAULO',
                'user_name' => 'marcelo.paulo',
                'password' => Hash::make('password'),
                'email' => 'marcelo.paulo@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'WILSON COMPANHIA',
                'user_name' => 'wilson.companhia',
                'password' => Hash::make('password'),
                'email' => 'wilson.companhia@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'ELISABETH MANUEL',
                'user_name' => 'elisabeth.manuel',
                'password' => Hash::make('password'),
                'email' => 'elisabeth.manuel@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'FERNANDO MUBONE',
                'user_name' => 'fernando.mubone',
                'password' => Hash::make('password'),
                'email' => 'fernando.mubone@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'JOÃO BELTRÃO',
                'user_name' => 'joao.beltrao',
                'password' => Hash::make('password'),
                'email' => 'joao.beltrao@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'PEDRO POLENE',
                'user_name' => 'pedro.polene',
                'password' => Hash::make('password'),
                'email' => 'pedro.polene@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'RICARDO CAMPAUNDE',
                'user_name' => 'ricardo.capaunde',
                'password' => Hash::make('password'),
                'email' => 'ricardo.capaunde@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'ZACARIAS BITCHO',
                'user_name' => 'zacarias.bitcho',
                'password' => Hash::make('password'),
                'email' => 'zacarias.bitcho@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'AMISSE AMADE',
                'user_name' => 'amisse.amade',
                'password' => Hash::make('password'),
                'email' => 'amisse.amade@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'CHICO JOAQUIM',
                'user_name' => 'chico.joaquim',
                'password' => Hash::make('password'),
                'email' => 'chico.joaquim@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'LATIFO MABALA',
                'user_name' => 'latifo.mabala',
                'password' => Hash::make('password'),
                'email' => 'latifo.mabala@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'SÉRGIO BONA',
                'user_name' => 'sergio.bona',
                'password' => Hash::make('password'),
                'email' => 'sergio.bona@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [
                'user_full_name' => 'INOQUE COLAÇO',
                'user_name' => 'inoque.colaco',
                'password' => Hash::make('password'),
                'email' => 'inoque.colaco@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'ARLINDO LOURENÇO',
                'user_name' => 'arlindo.lourenco',
                'password' => Hash::make('password'),
                'email' => 'arlindo.lourenco@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'ARTUR WIRE GUIDIONE',
                'user_name' => 'artur.guidione',
                'password' => Hash::make('password'),
                'email' => 'artur.guidione@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'HERMEN PINTO',
                'user_name' => 'hermen.pinto',
                'password' => Hash::make('password'),
                'email' => 'hermen.pinto@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'JAIME LUIS MEQUE',
                'user_name' => 'jaime.meque',
                'password' => Hash::make('password'),
                'email' => 'jaime.meque@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'LEONINO BAPTISTA',
                'user_name' => 'leonimo.baptista',
                'password' => Hash::make('password'),
                'email' => 'leonimo.baptista@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'MUCOLE AFONSO',
                'user_name' => 'mucole.afonso',
                'password' => Hash::make('password'),
                'email' => 'mucole.afonso@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'ROSA JOSÉ MUTENDA',
                'user_name' => 'rosa.mutemba',
                'password' => Hash::make('password'),
                'email' => 'rosa.mutemba@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'DOMINGOS DIAS',
                'user_name' => 'domingos.dias',
                'password' => Hash::make('password'),
                'email' => 'domingos.dias@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'BOAVNDA CHIMICA',
                'user_name' => 'boavinda.chimica',
                'password' => Hash::make('password'),
                'email' => 'boavinda.chimica@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'FERNANDO MAGUMISSE',
                'user_name' => 'fernando.maguimisse',
                'password' => Hash::make('password'),
                'email' => 'fernando.maguimisse@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'SOZINHO GINGA',
                'user_name' => 'sozinho.ginga',
                'password' => Hash::make('password'),
                'email' => 'sozinho.ginga@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'ISABEL VILANCULOS',
                'user_name' => 'isabel.vilanculos',
                'password' => Hash::make('password'),
                'email' => 'isabel.vilanculos@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'FILIPE CARVALHO ',
                'user_name' => 'filipe.carvalho',
                'password' => Hash::make('password'),
                'email' => 'filipe.carvalho@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'ARNALDO HENRIQUES',
                'user_name' => 'arnaldo.henriques',
                'password' => Hash::make('password'),
                'email' => 'arnaldo.henriques@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'JAIME MARTINHO FERNANDO',
                'user_name' => 'jaime.fernando',
                'password' => Hash::make('password'),
                'email' => 'jaime.fernando@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'MANUEL FRANCISCO JONE',
                'user_name' => 'manuel.jone',
                'password' => Hash::make('password'),
                'email' => 'manuel.jone@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'DÁRIO JOSÉ TAREMBA',
                'user_name' => 'dario.taremba',
                'password' => Hash::make('password'),
                'email' => 'dario.taremba@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'PEDRO JOAQUIM LUIS',
                'user_name' => 'pedro.luis',
                'password' => Hash::make('password'),
                'email' => 'pedro.luis@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'QUINCY MAJAMANDA',
                'user_name' => 'quincy.majamanda',
                'password' => Hash::make('password'),
                'email' => 'quincy.majamanda@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Joao Mupungue',
                'user_name' => 'joao.mupungue',
                'password' => Hash::make('password'),
                'email' => 'joao.mupungue@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Adamo Adamo',
                'user_name' => 'adamo.adamo',
                'password' => Hash::make('password'),
                'email' => 'adamo.adamo@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Domingos Jaime',
                'user_name' => 'domingos.jaime',
                'password' => Hash::make('password'),
                'email' => 'domingos.jaime@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Fiel Salimo',
                'user_name' => 'fiel.salimo',
                'password' => Hash::make('password'),
                'email' => 'fiel.salimo@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Domingos Arone',
                'user_name' => 'domingos.arone',
                'password' => Hash::make('password'),
                'email' => 'domingos.arone@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Paulo Castigo',
                'user_name' => 'paulo.castigo',
                'password' => Hash::make('password'),
                'email' => 'paulo.castigo@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'Jose João',
                'user_name' => 'jose.joao',
                'password' => Hash::make('password'),
                'email' => 'jose.joão@cgate.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'userfullname',
                'user_name' => 'Contractor',
                'password' => Hash::make('password'),
                'email' => 'cnt@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'userfullname',
                'user_name' => 'Contractor1',
                'password' => Hash::make('password'),
                'email' => 'cnt1@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
            [

                'user_full_name' => 'userfullname',
                'user_name' => 'access.control@cornelder.co.mz',
                'password' => Hash::make('password'),
                'email' => 'access.control@cornelder.co.mz',
                'created_by' => null,
                'created_at' => now(),
                'updated_by' => null,
                'updated_at' => now(),
            ],
        ]);
        
        $users = User::where('id','>',50)->get();
        foreach ($users as $user) {
            $user->assignRole('Security');
            $user->gate()->updateOrCreate(
                ['user_id' => $user->id],
                ['gate_id' => 1]
            );
        }
    }
}
